mkdir -p "A1/classical/bach/Air on the G String"
mkdir -p "A1/classical/bach/Inventions and Sinfonias"
mkdir -p "A1/classical/bach/Mass in B minor"
mkdir -p "A1/classical/Beethoven/Symphony No.5"
mkdir -p "A1/classical/Beethoven/Symphony No.9"
mkdir -p "A1/classical/Chopin/Etudes"
mkdir -p "A1/classical/Chopin/Minute Waltz"
mkdir -p "A1/classical/Chopin/Nocturne in E-flat major"
mkdir -p "A1/classical/Chopin/Preludes"
mkdir -p "A1/classical/Liszt/Les preludes"
mkdir -p "A1/classical/Tchaikovsky"
mkdir -p "A1/classical/Vivaldi/Four Seasons"
mkdir -p "A1/classical/Vivaldi/Violin concertos"
mkdir -p "A1/kpop/AOA/Excuse me"
mkdir -p "A1/kpop/AOA/Like a Cat"
mkdir -p "A1/kpop/AOA/Miniskirt"
mkdir -p "A1/kpop/BTS/Dynamite"
mkdir -p "A1/kpop/BTS/fake love"
mkdir -p "A1/kpop/BTS/mic drop"
mkdir -p "A1/kpop/BTS/Permission to dance"
mkdir -p "A1/kpop/GirlsGeneration/Forever 1"
mkdir -p "A1/kpop/GirlsGeneration/Gee"
mkdir -p "A1/kpop/GirlsGeneration/Into the Future"
mkdir -p "A1/kpop/GirlsGeneration/oh!"
mkdir -p "A1/kpop/In the morning"
mkdir -p "A1/kpop/itzy"
mkdir -p "A1/kpop/LOCO"
mkdir -p "A1/kpop/newJeans"
mkdir -p "A1/kpop/Not-Shy"
mkdir -p "A1/kpop/purplekiss"
mkdir -p "A1/kpop/redvelvet/Red Flavor"
mkdir -p "A1/kpop/redvelvet/Russian Roulette"
mkdir -p "A1/kpop/redvelvet/sneakers"
mkdir -p "A1/kpop/Twice/Alcohol-Free"
mkdir -p "A1/kpop/Twice/Feel Special"
mkdir -p "A1/kpop/Twice/Set Me Free"
mkdir -p "A1/kpop/Twice/Talk that Talk"
mkdir -p "A1/kpop/Twice/TT"
mkdir -p "A1/rap/Anarchy"
mkdir -p "A1/rap/Bang Yong-guk"
mkdir -p "A1/rap/dok2"
mkdir -p "A1/rap/Hannya"
mkdir -p "A1/rap/rm/life goes on"
mkdir -p "A1/rap/rm/love u hate u"
mkdir -p "A1/rap/so-yeon/Latata"
mkdir -p "A1/rap/so-yeon/My Bag"
mkdir -p "A1/rap/so-yeon/Tomboy"
mkdir -p "A1/rap/suga"
